---
title: "Hello World"
author: "Dr Massimiliano Canzi"
format: 
  revealjs:
    transition-speed: fast
    transition: fade
    background-transition: fade
    chalkboard: true
    slide-number: true
    show-slide-number: print
    touch: true
    controls: true
    theme: theme-mc.scss
    incremental: true
    footer: "`massimiliano.canzi@uni-konstanz.de` | Room G114, **Universität Konstanz**. Universitätstr. 10, 78467 Konstanz DE"
---

```{r}
#| include: false
library(tidyverse)
```

# Introduction

## Who

Dr Massimiliano (__Max__) Canzi

- `PhD`: University of Manchester 
- `MSc`: University of York 
- `MA`: University of Manchester 
- `BA`: University of Milan

__Interests__: `speech perception`, `rstats`, `quantitative linguistics`, `experimental linguistics`, `speech production`, 
`forensic speech science` 

## Who

Dr Massimiliano (__Max__) Canzi

- `What PMN? Processing phonological mismatch in semantics-free speech perception`
- `Do somatic features of a speaker mediate the perception of the speaker's voice?`
- `A quantitative analysis of acoustic differences between neutral and loud speech`

## Who 

`... ARE YOU?`

## Slides

Slides are made in `RStudio`, using `Quarto` and `RevealJS`

- The `slides` (as a .html file)
- The `code` for the slides (as a .qmd file, if applicable)

## Book 

- Winter, B. (2020). `Statistics for linguists: An introduction using R`. Routledge.
- Slides are supposed to work simply as a guideline -- most detailed content is found in the book.

## The meat and potatoes

- R
- RStudio

# Quant Methods?

`Did you know:` _The otter is one of the few mammals that use tools.
They have a loose patch of skin under their armpit to store both the food they've foraged and their rock to crack it open._

## Why Quantitative Methods?

Discuss...

## Objective or Subjective?

Discuss...

## You will

- Acquire `fundamental concepts` to conduct statistical analyses (in R.)  
- Learn fundamental concepts of `regression modelling`
- Learn to (losely) apply the above to `real linguistic data`
- Maybe some extra stuff if we have time? Who knows

## And now

. . .

Let's jump into `RStudio` for an overview
